ASK MARGIN x
PRINT "margin=";x
ASK ZONEWIDTH x
PRINT "zone width=";x
ASK WINDOW left,right,bottom,top
PRINT "window=";left;right;bottom;top
ASK VIEWPORT left,right,bottom,top
PRINT "viewport=";left;right;bottom;top
ASK DEVICE WINDOW left,right,bottom,top
PRINT "device window=";left;right;bottom;top
ASK DEVICE VIEWPORT left,right,bottom,top
PRINT "device viewport=";left;right;bottom;top
ASK AREA COLOR c
PRINT "area color=";c
ASK LINE COLOR c
PRINT "line color=";c
ASK POINT COLOR c
PRINT "point color=";c
ASK TEXT COLOR c
PRINT "text color=";c
ASK LINE STYLE x
PRINT "line style=";x
ASK POINT STYLE x
PRINT "point style=";x
ASK MAX LINE STYLE x
PRINT "max line style=";x
ASK MAX POINT STYLE x
PRINT "max point style=";X
ASK MAX COLOR x
PRINT "max color=";x
ASK TEXT HEIGHT x
PRINT "text height=";x
END

