OPTION ARITHMETIC COMPLEX
PICTURE D(n)
   IF n=depth THEN 
      PLOT POINTS: 0,0
   ELSE 
      DRAW D(n+1) WITH SCALE(r)
      DRAW D(n+1) WITH SCALE(1,-1)*SHIFT(-1)*SCALE(CONJ(r))*SHIFT(1)
   END IF
END PICTURE
LET i=SQR(-1)
LET r=(1+i)/2
SET WINDOW -1/2,3/2,-1,1
DRAW axes
SET POINT STYLE 1
ASK PIXEL SIZE(-1/2,-1;3/2,1) px,py
LET depth=CEIL(-LOG(px-1)/LOG(ABS(r)))
DRAW D(1)
END

