OPTION ARITHMETIC COMPLEX
PICTURE K(n)
   IF n=depth THEN 
      PLOT POINTS: 0,0
   ELSE 
      DRAW K(n+1) WITH SCALE(r)
      DRAW K(n+1) WITH SHIFT(-1)*SCALE(CONJ(r))*SHIFT(1)
   END IF
END PICTURE
LET i=SQR(-1)
LET r=(1+i)/2
SET WINDOW -1/2,3/2,-1,1
ASK PIXEL SIZE(-1/2,-1;3/2,1)  px,py
LET depth=INT(-LOG(px-1)/LOG(ABS(r)))
SET POINT STYLE 1
DRAW K(1)
END

