PICTURE vein(s)
   IF s<1/px THEN
      PLOT POINTS: 0,0
   ELSE
      DRAW vein(s*r) WITH SCALE(1,-1)*SCALE(r)*ROTATE(alfa)
      DRAW vein(s*2/3) WITH SHIFT(-1,0)*SCALE(1,-1)*SCALE(2/3)*SHIFT(1,0)
   END IF
END PICTURE
LET r=1/SQR(3)
LET alfa=ANGLE(1,1/SQR(3))
SET WINDOW 0,1,-1/2,1/2
ASK PIXEL SIZE(0,-1/2;1,1/2) px,py
SET POINT STYLE 1
DRAW vein(1)
END